_target_: src.model.mlp.DualHeadMLP

hidden_sizes: [2048, 2048]
output_size: 1

activation: 
  _target_: flax.linen.leaky_relu
  _partial_: True

kernel_init: 
  _target_: jax.nn.initializers.lecun_uniform

bias: True

initial_max_std: 0.2 
initial_min_std: 0.1
